// Generated by gencpp from file sys_diffeq/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SYS_DIFFEQ_MESSAGE_ADDTWOINTS_H
#define SYS_DIFFEQ_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sys_diffeq/AddTwoIntsRequest.h>
#include <sys_diffeq/AddTwoIntsResponse.h>


namespace sys_diffeq
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sys_diffeq


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sys_diffeq::AddTwoInts > {
  static const char* value()
  {
    return "2a4f2be7eea4eed058244c2783c6c637";
  }

  static const char* value(const ::sys_diffeq::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sys_diffeq::AddTwoInts > {
  static const char* value()
  {
    return "sys_diffeq/AddTwoInts";
  }

  static const char* value(const ::sys_diffeq::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sys_diffeq::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::sys_diffeq::AddTwoInts > 
template<>
struct MD5Sum< ::sys_diffeq::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sys_diffeq::AddTwoInts >::value();
  }
  static const char* value(const ::sys_diffeq::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sys_diffeq::AddTwoIntsRequest> should match 
// service_traits::DataType< ::sys_diffeq::AddTwoInts > 
template<>
struct DataType< ::sys_diffeq::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sys_diffeq::AddTwoInts >::value();
  }
  static const char* value(const ::sys_diffeq::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sys_diffeq::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::sys_diffeq::AddTwoInts > 
template<>
struct MD5Sum< ::sys_diffeq::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sys_diffeq::AddTwoInts >::value();
  }
  static const char* value(const ::sys_diffeq::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sys_diffeq::AddTwoIntsResponse> should match 
// service_traits::DataType< ::sys_diffeq::AddTwoInts > 
template<>
struct DataType< ::sys_diffeq::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sys_diffeq::AddTwoInts >::value();
  }
  static const char* value(const ::sys_diffeq::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYS_DIFFEQ_MESSAGE_ADDTWOINTS_H
