// Generated by gencpp from file sys_diffeq/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef SYS_DIFFEQ_MESSAGE_ADDTWOINTSRESPONSE_H
#define SYS_DIFFEQ_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sys_diffeq
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : x(0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : x(0)  {
    }



   typedef int64_t _x_type;
  _x_type x;




  typedef boost::shared_ptr< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::sys_diffeq::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::sys_diffeq::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::sys_diffeq::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sys_diffeq

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sys_diffeq': ['/home/smladmin/catkin_tmp/src/sys_diffeq/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b429044e1360891965aa67e074722c0e";
  }

  static const char* value(const ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb429044e13608919ULL;
  static const uint64_t static_value2 = 0x65aa67e074722c0eULL;
};

template<class ContainerAllocator>
struct DataType< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sys_diffeq/AddTwoIntsResponse";
  }

  static const char* value(const ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
\n\
";
  }

  static const char* value(const ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sys_diffeq::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYS_DIFFEQ_MESSAGE_ADDTWOINTSRESPONSE_H
