// Generated by gencpp from file sys_diffeq/SetState.msg
// DO NOT EDIT!


#ifndef SYS_DIFFEQ_MESSAGE_SETSTATE_H
#define SYS_DIFFEQ_MESSAGE_SETSTATE_H

#include <ros/service_traits.h>


#include <sys_diffeq/SetStateRequest.h>
#include <sys_diffeq/SetStateResponse.h>


namespace sys_diffeq
{

struct SetState
{

typedef SetStateRequest Request;
typedef SetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetState
} // namespace sys_diffeq


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sys_diffeq::SetState > {
  static const char* value()
  {
    return "b4a4569c4863c839d6e9f24980e2711d";
  }

  static const char* value(const ::sys_diffeq::SetState&) { return value(); }
};

template<>
struct DataType< ::sys_diffeq::SetState > {
  static const char* value()
  {
    return "sys_diffeq/SetState";
  }

  static const char* value(const ::sys_diffeq::SetState&) { return value(); }
};


// service_traits::MD5Sum< ::sys_diffeq::SetStateRequest> should match 
// service_traits::MD5Sum< ::sys_diffeq::SetState > 
template<>
struct MD5Sum< ::sys_diffeq::SetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sys_diffeq::SetState >::value();
  }
  static const char* value(const ::sys_diffeq::SetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sys_diffeq::SetStateRequest> should match 
// service_traits::DataType< ::sys_diffeq::SetState > 
template<>
struct DataType< ::sys_diffeq::SetStateRequest>
{
  static const char* value()
  {
    return DataType< ::sys_diffeq::SetState >::value();
  }
  static const char* value(const ::sys_diffeq::SetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sys_diffeq::SetStateResponse> should match 
// service_traits::MD5Sum< ::sys_diffeq::SetState > 
template<>
struct MD5Sum< ::sys_diffeq::SetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sys_diffeq::SetState >::value();
  }
  static const char* value(const ::sys_diffeq::SetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sys_diffeq::SetStateResponse> should match 
// service_traits::DataType< ::sys_diffeq::SetState > 
template<>
struct DataType< ::sys_diffeq::SetStateResponse>
{
  static const char* value()
  {
    return DataType< ::sys_diffeq::SetState >::value();
  }
  static const char* value(const ::sys_diffeq::SetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYS_DIFFEQ_MESSAGE_SETSTATE_H
